version: '3.7'

services:
  app:
    build: .
    command: bundle exec shotgun config.ru -o 0.0.0.0 -p 5000
    hostname: app
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'

volumes:
  app:
